### ISSUE TITLE
Availability of pre-packaged releases 

### ISSUE THREAD

**Issue by madpah** [sonatype-nexus-community/teamcity-nexusiq-plugin#18]
Most people don't want to build this plugin themselves - why is there not a regularly updated pre-built package available?

FYI: @hboutemy / @bhamail

**Comment by hboutemy** [comment]
release 1.0.0 done and published: https://github.com/sonatype-nexus-community/teamcity-nexusiq-plugin/releases/tag/teamcity-iq-plugin-1.0.0
